### PR TITLE
chore: upgrade gin to v1.5 version

### PR DESCRIPTION
**Pull request by appleboy**

### CODE REVIEW

**Comment by hantmac** [comment]
Hi, Thanks for your contributions, But we should push P&R to develop  branch first.
So, please open  a P&R that merge to develop. I will close this.

**Comment by appleboy** [comment]
I already changed the base branch to `develop`.

**Comment by hantmac** [comment]
> I already changed the base branch to `develop`.

Some questions:
- Why should we upgrade gin to v1.5 version?
- Is there any problem with the version being used？

**Comment by appleboy** [comment]
@hantmac I prefer to the master branch version for performance issues for gin. See the https://github.com/gin-gonic/gin/pull/2159

**Comment by tikazyq** [comment]
We decided to hold this PR as it's unproven that we can run the application flawlessly with this upgrade. We may proceed with this upgrade until we fully test it.

**Pull request closed without merging**
